version: '3.3'

services:
  mypod:
    build:
      context: .
    image: "mypod"
    container_name: "mypod"
    command: sh -c "php-fpm81 && chmod 777 /var/run/php/php81-fpm.sock && nginx -g 'daemon off;'"
    environment:
      MYPOD_DOMAIN: http://localhost:8000
    volumes:
      - ./podcasts:/usr/share/nginx/html/podcasts
    ports:
      - "8000:80"
      - "8001:443"
    restart: unless-stopped
